platform :ios, '7.0'

pod 'JTCalendar', '~> 2.1.5'
pod 'Masonry', '~> 0.6.4'
pod 'UIAlertView+Blocks', '~> 0.9'
pod 'AFNetworking', '~> 3.0.4'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'MJExtension', '~> 3.0.10'
pod 'WMPageController', '~> 1.6.2'
pod 'Canvas', '~> 0.1.2'
pod 'THLabel', '~> 1.4.7'